# Generated by Django 4.2.6 on 2024-05-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskdo", "0004_alter_user_email_alter_user_mobile_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=300)),
                ("product_price", models.IntegerField(max_length=10)),
                ("icon", models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
